<Project>
  <PropertyGroup>
    <VrcExecutionProvider Condition="'$(VrcExecutionProvider)' == ''">CPU</VrcExecutionProvider>
    <BaseIntermediateOutputPath>obj\$(VrcExecutionProvider)\</BaseIntermediateOutputPath>
    <BaseOutputPath>bin\$(VrcExecutionProvider)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\obj\**;$(MSBuildProjectDirectory)\bin\**</DefaultItemExcludes>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) 2026 VRC-Fisher contributors</Copyright>
  </PropertyGroup>
</Project>
